/** @format */

import { Space_Grotesk } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weights: [400, 500, 700],
});

export const metadata = {
  title: "Single-page developer portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={twMerge(
          spaceGrotesk.className,
          "antialiased",
          "bg-primary",
          "text-white"
        )}
      >
        {children}
      </body>
    </html>
  );
}
